// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: electronic_product/electronic_product_v1.proto

package electronic_product_v1

import (
	common "github.com/mechta-market/e-product/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyStatus int32

const (
	KeyStatus_new       KeyStatus = 0
	KeyStatus_activated KeyStatus = 1
)

// Enum value maps for KeyStatus.
var (
	KeyStatus_name = map[int32]string{
		0: "new",
		1: "activated",
	}
	KeyStatus_value = map[string]int32{
		"new":       0,
		"activated": 1,
	}
)

func (x KeyStatus) Enum() *KeyStatus {
	p := new(KeyStatus)
	*p = x
	return p
}

func (x KeyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_electronic_product_electronic_product_v1_proto_enumTypes[0].Descriptor()
}

func (KeyStatus) Type() protoreflect.EnumType {
	return &file_electronic_product_electronic_product_v1_proto_enumTypes[0]
}

func (x KeyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyStatus.Descriptor instead.
func (KeyStatus) EnumDescriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{0}
}

// Load
type KeyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyItem) Reset() {
	*x = KeyItem{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyItem) ProtoMessage() {}

func (x *KeyItem) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyItem.ProtoReflect.Descriptor instead.
func (*KeyItem) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{0}
}

func (x *KeyItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LoadKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyItem             `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKeyReq) Reset() {
	*x = LoadKeyReq{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKeyReq) ProtoMessage() {}

func (x *LoadKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKeyReq.ProtoReflect.Descriptor instead.
func (*LoadKeyReq) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{1}
}

func (x *LoadKeyReq) GetKeys() []*KeyItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyResponseItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId        string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProductId         string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerPhone     string                 `protobuf:"bytes,6,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Status            KeyStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=electronic_product_v1.KeyStatus" json:"status,omitempty"`
	OrderId           string                 `protobuf:"bytes,8,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProviderProductId string                 `protobuf:"bytes,9,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KeyResponseItem) Reset() {
	*x = KeyResponseItem{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponseItem) ProtoMessage() {}

func (x *KeyResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponseItem.ProtoReflect.Descriptor instead.
func (*KeyResponseItem) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{2}
}

func (x *KeyResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyResponseItem) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *KeyResponseItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyResponseItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KeyResponseItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KeyResponseItem) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *KeyResponseItem) GetStatus() KeyStatus {
	if x != nil {
		return x.Status
	}
	return KeyStatus_new
}

func (x *KeyResponseItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KeyResponseItem) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

type LoadKeyRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyResponseItem     `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKeyRep) Reset() {
	*x = LoadKeyRep{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKeyRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKeyRep) ProtoMessage() {}

func (x *LoadKeyRep) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKeyRep.ProtoReflect.Descriptor instead.
func (*LoadKeyRep) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{3}
}

func (x *LoadKeyRep) GetKeys() []*KeyResponseItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

// List
type KeyListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    *string                `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3,oneof" json:"provider_id,omitempty"`
	Status        *KeyStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=electronic_product_v1.KeyStatus,oneof" json:"status,omitempty"`
	OrderId       *string                `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,4,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyListReq) Reset() {
	*x = KeyListReq{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListReq) ProtoMessage() {}

func (x *KeyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListReq.ProtoReflect.Descriptor instead.
func (*KeyListReq) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{4}
}

func (x *KeyListReq) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *KeyListReq) GetStatus() KeyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KeyStatus_new
}

func (x *KeyListReq) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *KeyListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

type KeyListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Keys           []*KeyResponseItem       `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyListRep) Reset() {
	*x = KeyListRep{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListRep) ProtoMessage() {}

func (x *KeyListRep) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListRep.ProtoReflect.Descriptor instead.
func (*KeyListRep) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{5}
}

func (x *KeyListRep) GetKeys() []*KeyResponseItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeyListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

// Get
type KeyGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGetReq) Reset() {
	*x = KeyGetReq{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGetReq) ProtoMessage() {}

func (x *KeyGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGetReq.ProtoReflect.Descriptor instead.
func (*KeyGetReq) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{6}
}

func (x *KeyGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KeyGetRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *KeyResponseItem       `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGetRep) Reset() {
	*x = KeyGetRep{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGetRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGetRep) ProtoMessage() {}

func (x *KeyGetRep) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGetRep.ProtoReflect.Descriptor instead.
func (*KeyGetRep) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{7}
}

func (x *KeyGetRep) GetKey() *KeyResponseItem {
	if x != nil {
		return x.Key
	}
	return nil
}

// Activate
type KeyActivateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,3,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyActivateReq) Reset() {
	*x = KeyActivateReq{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyActivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyActivateReq) ProtoMessage() {}

func (x *KeyActivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyActivateReq.ProtoReflect.Descriptor instead.
func (*KeyActivateReq) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{8}
}

func (x *KeyActivateReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyActivateReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KeyActivateReq) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

type KeyActivateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyActivateRep) Reset() {
	*x = KeyActivateRep{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyActivateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyActivateRep) ProtoMessage() {}

func (x *KeyActivateRep) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyActivateRep.ProtoReflect.Descriptor instead.
func (*KeyActivateRep) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{9}
}

func (x *KeyActivateRep) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// mdm search
type GetByProductIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByProductIDReq) Reset() {
	*x = GetByProductIDReq{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByProductIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByProductIDReq) ProtoMessage() {}

func (x *GetByProductIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByProductIDReq.ProtoReflect.Descriptor instead.
func (*GetByProductIDReq) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{10}
}

func (x *GetByProductIDReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetByProductIDRep struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProviderId        string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderProductId string                 `protobuf:"bytes,3,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	PromotionKey      string                 `protobuf:"bytes,4,opt,name=promotion_key,json=promotionKey,proto3" json:"promotion_key,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetByProductIDRep) Reset() {
	*x = GetByProductIDRep{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByProductIDRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByProductIDRep) ProtoMessage() {}

func (x *GetByProductIDRep) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByProductIDRep.ProtoReflect.Descriptor instead.
func (*GetByProductIDRep) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{11}
}

func (x *GetByProductIDRep) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetByProductIDRep) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetByProductIDRep) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

func (x *GetByProductIDRep) GetPromotionKey() string {
	if x != nil {
		return x.PromotionKey
	}
	return ""
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,2,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{12}
}

func (x *CreateOrderReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderReq) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *CreateOrderReq) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRep struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId        string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProductId         string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProviderProductId string                 `protobuf:"bytes,4,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	OrderId           string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerPhone     string                 `protobuf:"bytes,6,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Status            KeyStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=electronic_product_v1.KeyStatus" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderRep) Reset() {
	*x = CreateOrderRep{}
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRep) ProtoMessage() {}

func (x *CreateOrderRep) ProtoReflect() protoreflect.Message {
	mi := &file_electronic_product_electronic_product_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRep.ProtoReflect.Descriptor instead.
func (*CreateOrderRep) Descriptor() ([]byte, []int) {
	return file_electronic_product_electronic_product_v1_proto_rawDescGZIP(), []int{13}
}

func (x *CreateOrderRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRep) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CreateOrderRep) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderRep) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

func (x *CreateOrderRep) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderRep) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *CreateOrderRep) GetStatus() KeyStatus {
	if x != nil {
		return x.Status
	}
	return KeyStatus_new
}

var File_electronic_product_electronic_product_v1_proto protoreflect.FileDescriptor

const file_electronic_product_electronic_product_v1_proto_rawDesc = "" +
	"\n" +
	".electronic_product/electronic_product_v1.proto\x12\x15electronic_product_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\">\n" +
	"\aKeyItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"@\n" +
	"\n" +
	"LoadKeyReq\x122\n" +
	"\x04keys\x18\x01 \x03(\v2\x1e.electronic_product_v1.KeyItemR\x04keys\"\x83\x03\n" +
	"\x0fKeyResponseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0ecustomer_phone\x18\x06 \x01(\tR\rcustomerPhone\x128\n" +
	"\x06status\x18\a \x01(\x0e2 .electronic_product_v1.KeyStatusR\x06status\x12\x19\n" +
	"\border_id\x18\b \x01(\tR\aorderId\x12.\n" +
	"\x13provider_product_id\x18\t \x01(\tR\x11providerProductId\"H\n" +
	"\n" +
	"LoadKeyRep\x12:\n" +
	"\x04keys\x18\x01 \x03(\v2&.electronic_product_v1.KeyResponseItemR\x04keys\"\xf0\x01\n" +
	"\n" +
	"KeyListReq\x12$\n" +
	"\vprovider_id\x18\x01 \x01(\tH\x00R\n" +
	"providerId\x88\x01\x01\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2 .electronic_product_v1.KeyStatusH\x01R\x06status\x88\x01\x01\x12\x1e\n" +
	"\border_id\x18\x03 \x01(\tH\x02R\aorderId\x88\x01\x01\x125\n" +
	"\vlist_params\x18\x04 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParamsB\x0e\n" +
	"\f_provider_idB\t\n" +
	"\a_statusB\v\n" +
	"\t_order_id\"\x8b\x01\n" +
	"\n" +
	"KeyListRep\x12:\n" +
	"\x04keys\x18\x01 \x03(\v2&.electronic_product_v1.KeyResponseItemR\x04keys\x12A\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\"\x1b\n" +
	"\tKeyGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\tKeyGetRep\x12=\n" +
	"\x03key\x18\x01 \x01(\v2&.electronic_product_v1.KeyResponseItemH\x00R\x03key\x88\x01\x01B\x06\n" +
	"\x04_key\"q\n" +
	"\x0eKeyActivateReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12%\n" +
	"\x0ecustomer_phone\x18\x03 \x01(\tR\rcustomerPhone\"&\n" +
	"\x0eKeyActivateRep\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"2\n" +
	"\x11GetByProductIDReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\xa8\x01\n" +
	"\x11GetByProductIDRep\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12.\n" +
	"\x13provider_product_id\x18\x03 \x01(\tR\x11providerProductId\x12#\n" +
	"\rpromotion_key\x18\x04 \x01(\tR\fpromotionKey\"r\n" +
	"\x0eCreateOrderReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12%\n" +
	"\x0ecustomer_phone\x18\x02 \x01(\tR\rcustomerPhone\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"\x8c\x02\n" +
	"\x0eCreateOrderRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12.\n" +
	"\x13provider_product_id\x18\x04 \x01(\tR\x11providerProductId\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12%\n" +
	"\x0ecustomer_phone\x18\x06 \x01(\tR\rcustomerPhone\x128\n" +
	"\x06status\x18\a \x01(\x0e2 .electronic_product_v1.KeyStatusR\x06status*#\n" +
	"\tKeyStatus\x12\a\n" +
	"\x03new\x10\x00\x12\r\n" +
	"\tactivated\x10\x012\x93\x04\n" +
	"\x03Key\x12]\n" +
	"\x04Load\x12!.electronic_product_v1.LoadKeyReq\x1a!.electronic_product_v1.LoadKeyRep\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/key\x12Z\n" +
	"\x04List\x12!.electronic_product_v1.KeyListReq\x1a!.electronic_product_v1.KeyListRep\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/key\x12\\\n" +
	"\x03Get\x12 .electronic_product_v1.KeyGetReq\x1a .electronic_product_v1.KeyGetRep\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/key/{id}\x12r\n" +
	"\bActivate\x12%.electronic_product_v1.KeyActivateReq\x1a%.electronic_product_v1.KeyActivateRep\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/key/activate\x12\x7f\n" +
	"\x0eGetByProductID\x12(.electronic_product_v1.GetByProductIDReq\x1a(.electronic_product_v1.GetByProductIDRep\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/mdm/{product_id}B\x18Z\x16/electronic_product_v1b\x06proto3"

var (
	file_electronic_product_electronic_product_v1_proto_rawDescOnce sync.Once
	file_electronic_product_electronic_product_v1_proto_rawDescData []byte
)

func file_electronic_product_electronic_product_v1_proto_rawDescGZIP() []byte {
	file_electronic_product_electronic_product_v1_proto_rawDescOnce.Do(func() {
		file_electronic_product_electronic_product_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_electronic_product_electronic_product_v1_proto_rawDesc), len(file_electronic_product_electronic_product_v1_proto_rawDesc)))
	})
	return file_electronic_product_electronic_product_v1_proto_rawDescData
}

var file_electronic_product_electronic_product_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_electronic_product_electronic_product_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_electronic_product_electronic_product_v1_proto_goTypes = []any{
	(KeyStatus)(0),                  // 0: electronic_product_v1.KeyStatus
	(*KeyItem)(nil),                 // 1: electronic_product_v1.KeyItem
	(*LoadKeyReq)(nil),              // 2: electronic_product_v1.LoadKeyReq
	(*KeyResponseItem)(nil),         // 3: electronic_product_v1.KeyResponseItem
	(*LoadKeyRep)(nil),              // 4: electronic_product_v1.LoadKeyRep
	(*KeyListReq)(nil),              // 5: electronic_product_v1.KeyListReq
	(*KeyListRep)(nil),              // 6: electronic_product_v1.KeyListRep
	(*KeyGetReq)(nil),               // 7: electronic_product_v1.KeyGetReq
	(*KeyGetRep)(nil),               // 8: electronic_product_v1.KeyGetRep
	(*KeyActivateReq)(nil),          // 9: electronic_product_v1.KeyActivateReq
	(*KeyActivateRep)(nil),          // 10: electronic_product_v1.KeyActivateRep
	(*GetByProductIDReq)(nil),       // 11: electronic_product_v1.GetByProductIDReq
	(*GetByProductIDRep)(nil),       // 12: electronic_product_v1.GetByProductIDRep
	(*CreateOrderReq)(nil),          // 13: electronic_product_v1.CreateOrderReq
	(*CreateOrderRep)(nil),          // 14: electronic_product_v1.CreateOrderRep
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 16: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 17: common.PaginationInfoSt
}
var file_electronic_product_electronic_product_v1_proto_depIdxs = []int32{
	1,  // 0: electronic_product_v1.LoadKeyReq.keys:type_name -> electronic_product_v1.KeyItem
	15, // 1: electronic_product_v1.KeyResponseItem.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: electronic_product_v1.KeyResponseItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: electronic_product_v1.KeyResponseItem.status:type_name -> electronic_product_v1.KeyStatus
	3,  // 4: electronic_product_v1.LoadKeyRep.keys:type_name -> electronic_product_v1.KeyResponseItem
	0,  // 5: electronic_product_v1.KeyListReq.status:type_name -> electronic_product_v1.KeyStatus
	16, // 6: electronic_product_v1.KeyListReq.list_params:type_name -> common.ListParamsSt
	3,  // 7: electronic_product_v1.KeyListRep.keys:type_name -> electronic_product_v1.KeyResponseItem
	17, // 8: electronic_product_v1.KeyListRep.pagination_info:type_name -> common.PaginationInfoSt
	3,  // 9: electronic_product_v1.KeyGetRep.key:type_name -> electronic_product_v1.KeyResponseItem
	0,  // 10: electronic_product_v1.CreateOrderRep.status:type_name -> electronic_product_v1.KeyStatus
	2,  // 11: electronic_product_v1.Key.Load:input_type -> electronic_product_v1.LoadKeyReq
	5,  // 12: electronic_product_v1.Key.List:input_type -> electronic_product_v1.KeyListReq
	7,  // 13: electronic_product_v1.Key.Get:input_type -> electronic_product_v1.KeyGetReq
	9,  // 14: electronic_product_v1.Key.Activate:input_type -> electronic_product_v1.KeyActivateReq
	11, // 15: electronic_product_v1.Key.GetByProductID:input_type -> electronic_product_v1.GetByProductIDReq
	4,  // 16: electronic_product_v1.Key.Load:output_type -> electronic_product_v1.LoadKeyRep
	6,  // 17: electronic_product_v1.Key.List:output_type -> electronic_product_v1.KeyListRep
	8,  // 18: electronic_product_v1.Key.Get:output_type -> electronic_product_v1.KeyGetRep
	10, // 19: electronic_product_v1.Key.Activate:output_type -> electronic_product_v1.KeyActivateRep
	12, // 20: electronic_product_v1.Key.GetByProductID:output_type -> electronic_product_v1.GetByProductIDRep
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_electronic_product_electronic_product_v1_proto_init() }
func file_electronic_product_electronic_product_v1_proto_init() {
	if File_electronic_product_electronic_product_v1_proto != nil {
		return
	}
	file_electronic_product_electronic_product_v1_proto_msgTypes[4].OneofWrappers = []any{}
	file_electronic_product_electronic_product_v1_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_electronic_product_electronic_product_v1_proto_rawDesc), len(file_electronic_product_electronic_product_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_electronic_product_electronic_product_v1_proto_goTypes,
		DependencyIndexes: file_electronic_product_electronic_product_v1_proto_depIdxs,
		EnumInfos:         file_electronic_product_electronic_product_v1_proto_enumTypes,
		MessageInfos:      file_electronic_product_electronic_product_v1_proto_msgTypes,
	}.Build()
	File_electronic_product_electronic_product_v1_proto = out.File
	file_electronic_product_electronic_product_v1_proto_goTypes = nil
	file_electronic_product_electronic_product_v1_proto_depIdxs = nil
}
