// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: e_product/e_product_v1.proto

package e_product_v1

import (
	common "github.com/mechta-market/e-product/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyStatus int32

const (
	KeyStatus_new       KeyStatus = 0
	KeyStatus_activated KeyStatus = 1
)

// Enum value maps for KeyStatus.
var (
	KeyStatus_name = map[int32]string{
		0: "new",
		1: "activated",
	}
	KeyStatus_value = map[string]int32{
		"new":       0,
		"activated": 1,
	}
)

func (x KeyStatus) Enum() *KeyStatus {
	p := new(KeyStatus)
	*p = x
	return p
}

func (x KeyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_e_product_e_product_v1_proto_enumTypes[0].Descriptor()
}

func (KeyStatus) Type() protoreflect.EnumType {
	return &file_e_product_e_product_v1_proto_enumTypes[0]
}

func (x KeyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyStatus.Descriptor instead.
func (KeyStatus) EnumDescriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{0}
}

// Load
type KeyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyItem) Reset() {
	*x = KeyItem{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyItem) ProtoMessage() {}

func (x *KeyItem) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyItem.ProtoReflect.Descriptor instead.
func (*KeyItem) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{0}
}

func (x *KeyItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LoadKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyItem             `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKeyReq) Reset() {
	*x = LoadKeyReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKeyReq) ProtoMessage() {}

func (x *LoadKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKeyReq.ProtoReflect.Descriptor instead.
func (*LoadKeyReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{1}
}

func (x *LoadKeyReq) GetKeys() []*KeyItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyResponseItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId        string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProductId         string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerPhone     string                 `protobuf:"bytes,6,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Status            KeyStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=e_product_v1.KeyStatus" json:"status,omitempty"`
	OrderId           string                 `protobuf:"bytes,8,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProviderProductId string                 `protobuf:"bytes,9,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	ProviderOrderId   string                 `protobuf:"bytes,10,opt,name=provider_order_id,json=providerOrderId,proto3" json:"provider_order_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KeyResponseItem) Reset() {
	*x = KeyResponseItem{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponseItem) ProtoMessage() {}

func (x *KeyResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponseItem.ProtoReflect.Descriptor instead.
func (*KeyResponseItem) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{2}
}

func (x *KeyResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyResponseItem) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *KeyResponseItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyResponseItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KeyResponseItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KeyResponseItem) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *KeyResponseItem) GetStatus() KeyStatus {
	if x != nil {
		return x.Status
	}
	return KeyStatus_new
}

func (x *KeyResponseItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KeyResponseItem) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

func (x *KeyResponseItem) GetProviderOrderId() string {
	if x != nil {
		return x.ProviderOrderId
	}
	return ""
}

type LoadKeyRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyResponseItem     `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKeyRep) Reset() {
	*x = LoadKeyRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKeyRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKeyRep) ProtoMessage() {}

func (x *LoadKeyRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKeyRep.ProtoReflect.Descriptor instead.
func (*LoadKeyRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{3}
}

func (x *LoadKeyRep) GetKeys() []*KeyResponseItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

// List
type KeyListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    *string                `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3,oneof" json:"provider_id,omitempty"`
	Status        *KeyStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=e_product_v1.KeyStatus,oneof" json:"status,omitempty"`
	OrderId       *string                `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,4,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyListReq) Reset() {
	*x = KeyListReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListReq) ProtoMessage() {}

func (x *KeyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListReq.ProtoReflect.Descriptor instead.
func (*KeyListReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{4}
}

func (x *KeyListReq) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *KeyListReq) GetStatus() KeyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KeyStatus_new
}

func (x *KeyListReq) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *KeyListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

type KeyListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Keys           []*KeyResponseItem       `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyListRep) Reset() {
	*x = KeyListRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListRep) ProtoMessage() {}

func (x *KeyListRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListRep.ProtoReflect.Descriptor instead.
func (*KeyListRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{5}
}

func (x *KeyListRep) GetKeys() []*KeyResponseItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeyListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

// Get
type KeyGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGetReq) Reset() {
	*x = KeyGetReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGetReq) ProtoMessage() {}

func (x *KeyGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGetReq.ProtoReflect.Descriptor instead.
func (*KeyGetReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{6}
}

func (x *KeyGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KeyGetRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *KeyResponseItem       `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGetRep) Reset() {
	*x = KeyGetRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGetRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGetRep) ProtoMessage() {}

func (x *KeyGetRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGetRep.ProtoReflect.Descriptor instead.
func (*KeyGetRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{7}
}

func (x *KeyGetRep) GetKey() *KeyResponseItem {
	if x != nil {
		return x.Key
	}
	return nil
}

// Activate
type KeyActivateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,3,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyActivateReq) Reset() {
	*x = KeyActivateReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyActivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyActivateReq) ProtoMessage() {}

func (x *KeyActivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyActivateReq.ProtoReflect.Descriptor instead.
func (*KeyActivateReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{8}
}

func (x *KeyActivateReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyActivateReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KeyActivateReq) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

type KeyActivateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyActivateRep) Reset() {
	*x = KeyActivateRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyActivateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyActivateRep) ProtoMessage() {}

func (x *KeyActivateRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyActivateRep.ProtoReflect.Descriptor instead.
func (*KeyActivateRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{9}
}

func (x *KeyActivateRep) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// mdm search
type GetByProductIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByProductIDReq) Reset() {
	*x = GetByProductIDReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByProductIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByProductIDReq) ProtoMessage() {}

func (x *GetByProductIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByProductIDReq.ProtoReflect.Descriptor instead.
func (*GetByProductIDReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{10}
}

func (x *GetByProductIDReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type GetByProductIDRep struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ProductId                 string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProviderId                string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderProductId         string                 `protobuf:"bytes,3,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	PromotionKey              string                 `protobuf:"bytes,4,opt,name=promotion_key,json=promotionKey,proto3" json:"promotion_key,omitempty"`
	ProviderExternalProductId string                 `protobuf:"bytes,5,opt,name=provider_external_product_id,json=providerExternalProductId,proto3" json:"provider_external_product_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetByProductIDRep) Reset() {
	*x = GetByProductIDRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByProductIDRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByProductIDRep) ProtoMessage() {}

func (x *GetByProductIDRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByProductIDRep.ProtoReflect.Descriptor instead.
func (*GetByProductIDRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{11}
}

func (x *GetByProductIDRep) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetByProductIDRep) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetByProductIDRep) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

func (x *GetByProductIDRep) GetPromotionKey() string {
	if x != nil {
		return x.PromotionKey
	}
	return ""
}

func (x *GetByProductIDRep) GetProviderExternalProductId() string {
	if x != nil {
		return x.ProviderExternalProductId
	}
	return ""
}

type GetCatalogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogReq) Reset() {
	*x = GetCatalogReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogReq) ProtoMessage() {}

func (x *GetCatalogReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogReq.ProtoReflect.Descriptor instead.
func (*GetCatalogReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{12}
}

func (x *GetCatalogReq) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type GetCatalogRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRep) Reset() {
	*x = GetCatalogRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRep) ProtoMessage() {}

func (x *GetCatalogRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRep.ProtoReflect.Descriptor instead.
func (*GetCatalogRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{13}
}

func (x *GetCatalogRep) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CatalogItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductId         string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProviderProductId string                 `protobuf:"bytes,2,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	Slug              string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Name              string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CatalogItem) Reset() {
	*x = CatalogItem{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogItem) ProtoMessage() {}

func (x *CatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogItem.ProtoReflect.Descriptor instead.
func (*CatalogItem) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{14}
}

func (x *CatalogItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CatalogItem) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

func (x *CatalogItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CatalogItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,2,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{15}
}

func (x *CreateOrderReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateOrderReq) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *CreateOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CreateOrderRep struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	ProviderId        *string                `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3,oneof" json:"provider_id,omitempty"`
	ProductId         *string                `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	ProviderProductId *string                `protobuf:"bytes,4,opt,name=provider_product_id,json=providerProductId,proto3,oneof" json:"provider_product_id,omitempty"`
	OrderId           *string                `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	CustomerPhone     *string                `protobuf:"bytes,6,opt,name=customer_phone,json=customerPhone,proto3,oneof" json:"customer_phone,omitempty"`
	Status            *KeyStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=e_product_v1.KeyStatus,oneof" json:"status,omitempty"`
	ProviderOrderId   *string                `protobuf:"bytes,8,opt,name=provider_order_id,json=providerOrderId,proto3,oneof" json:"provider_order_id,omitempty"`
	Value             string                 `protobuf:"bytes,9,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateOrderRep) Reset() {
	*x = CreateOrderRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRep) ProtoMessage() {}

func (x *CreateOrderRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRep.ProtoReflect.Descriptor instead.
func (*CreateOrderRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{16}
}

func (x *CreateOrderRep) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *CreateOrderRep) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *CreateOrderRep) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

func (x *CreateOrderRep) GetProviderProductId() string {
	if x != nil && x.ProviderProductId != nil {
		return *x.ProviderProductId
	}
	return ""
}

func (x *CreateOrderRep) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *CreateOrderRep) GetCustomerPhone() string {
	if x != nil && x.CustomerPhone != nil {
		return *x.CustomerPhone
	}
	return ""
}

func (x *CreateOrderRep) GetStatus() KeyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KeyStatus_new
}

func (x *CreateOrderRep) GetProviderOrderId() string {
	if x != nil && x.ProviderOrderId != nil {
		return *x.ProviderOrderId
	}
	return ""
}

func (x *CreateOrderRep) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{17}
}

func (x *CancelOrderReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRep) Reset() {
	*x = CancelOrderRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRep) ProtoMessage() {}

func (x *CancelOrderRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRep.ProtoReflect.Descriptor instead.
func (*CancelOrderRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{18}
}

func (x *CancelOrderRep) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_e_product_e_product_v1_proto protoreflect.FileDescriptor

const file_e_product_e_product_v1_proto_rawDesc = "" +
	"\n" +
	"\x1ce_product/e_product_v1.proto\x12\fe_product_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\">\n" +
	"\aKeyItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"7\n" +
	"\n" +
	"LoadKeyReq\x12)\n" +
	"\x04keys\x18\x01 \x03(\v2\x15.e_product_v1.KeyItemR\x04keys\"\xa6\x03\n" +
	"\x0fKeyResponseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0ecustomer_phone\x18\x06 \x01(\tR\rcustomerPhone\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.e_product_v1.KeyStatusR\x06status\x12\x19\n" +
	"\border_id\x18\b \x01(\tR\aorderId\x12.\n" +
	"\x13provider_product_id\x18\t \x01(\tR\x11providerProductId\x12*\n" +
	"\x11provider_order_id\x18\n" +
	" \x01(\tR\x0fproviderOrderId\"?\n" +
	"\n" +
	"LoadKeyRep\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.e_product_v1.KeyResponseItemR\x04keys\"\xe7\x01\n" +
	"\n" +
	"KeyListReq\x12$\n" +
	"\vprovider_id\x18\x01 \x01(\tH\x00R\n" +
	"providerId\x88\x01\x01\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.e_product_v1.KeyStatusH\x01R\x06status\x88\x01\x01\x12\x1e\n" +
	"\border_id\x18\x03 \x01(\tH\x02R\aorderId\x88\x01\x01\x125\n" +
	"\vlist_params\x18\x04 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParamsB\x0e\n" +
	"\f_provider_idB\t\n" +
	"\a_statusB\v\n" +
	"\t_order_id\"\x82\x01\n" +
	"\n" +
	"KeyListRep\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.e_product_v1.KeyResponseItemR\x04keys\x12A\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\"\x1b\n" +
	"\tKeyGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\tKeyGetRep\x124\n" +
	"\x03key\x18\x01 \x01(\v2\x1d.e_product_v1.KeyResponseItemH\x00R\x03key\x88\x01\x01B\x06\n" +
	"\x04_key\"q\n" +
	"\x0eKeyActivateReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12%\n" +
	"\x0ecustomer_phone\x18\x03 \x01(\tR\rcustomerPhone\"&\n" +
	"\x0eKeyActivateRep\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"2\n" +
	"\x11GetByProductIDReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\xe9\x01\n" +
	"\x11GetByProductIDRep\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12.\n" +
	"\x13provider_product_id\x18\x03 \x01(\tR\x11providerProductId\x12#\n" +
	"\rpromotion_key\x18\x04 \x01(\tR\fpromotionKey\x12?\n" +
	"\x1cprovider_external_product_id\x18\x05 \x01(\tR\x19providerExternalProductId\"0\n" +
	"\rGetCatalogReq\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"@\n" +
	"\rGetCatalogRep\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.e_product_v1.CatalogItemR\x05items\"\x84\x01\n" +
	"\vCatalogItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12.\n" +
	"\x13provider_product_id\x18\x02 \x01(\tR\x11providerProductId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"q\n" +
	"\x0eCreateOrderReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12%\n" +
	"\x0ecustomer_phone\x18\x02 \x01(\tR\rcustomerPhone\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"\xec\x03\n" +
	"\x0eCreateOrderRep\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12$\n" +
	"\vprovider_id\x18\x02 \x01(\tH\x01R\n" +
	"providerId\x88\x01\x01\x12\"\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tH\x02R\tproductId\x88\x01\x01\x123\n" +
	"\x13provider_product_id\x18\x04 \x01(\tH\x03R\x11providerProductId\x88\x01\x01\x12\x1e\n" +
	"\border_id\x18\x05 \x01(\tH\x04R\aorderId\x88\x01\x01\x12*\n" +
	"\x0ecustomer_phone\x18\x06 \x01(\tH\x05R\rcustomerPhone\x88\x01\x01\x124\n" +
	"\x06status\x18\a \x01(\x0e2\x17.e_product_v1.KeyStatusH\x06R\x06status\x88\x01\x01\x12/\n" +
	"\x11provider_order_id\x18\b \x01(\tH\aR\x0fproviderOrderId\x88\x01\x01\x12\x14\n" +
	"\x05value\x18\t \x01(\tR\x05valueB\x05\n" +
	"\x03_idB\x0e\n" +
	"\f_provider_idB\r\n" +
	"\v_product_idB\x16\n" +
	"\x14_provider_product_idB\v\n" +
	"\t_order_idB\x11\n" +
	"\x0f_customer_phoneB\t\n" +
	"\a_statusB\x14\n" +
	"\x12_provider_order_id\"+\n" +
	"\x0eCancelOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"+\n" +
	"\x0eCancelOrderRep\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId*#\n" +
	"\tKeyStatus\x12\a\n" +
	"\x03new\x10\x00\x12\r\n" +
	"\tactivated\x10\x012\xef\x05\n" +
	"\x03Key\x12K\n" +
	"\x04Load\x12\x18.e_product_v1.LoadKeyReq\x1a\x18.e_product_v1.LoadKeyRep\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/key\x12H\n" +
	"\x04List\x12\x18.e_product_v1.KeyListReq\x1a\x18.e_product_v1.KeyListRep\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/key\x12J\n" +
	"\x03Get\x12\x17.e_product_v1.KeyGetReq\x1a\x17.e_product_v1.KeyGetRep\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/key/{id}\x12`\n" +
	"\bActivate\x12\x1c.e_product_v1.KeyActivateReq\x1a\x1c.e_product_v1.KeyActivateRep\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/key/activate\x12m\n" +
	"\x0eGetByProductID\x12\x1f.e_product_v1.GetByProductIDReq\x1a\x1f.e_product_v1.GetByProductIDRep\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/mdm/{product_id}\x12c\n" +
	"\vCreateOrder\x12\x1c.e_product_v1.CreateOrderReq\x1a\x1c.e_product_v1.CreateOrderRep\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/key/provider\x12j\n" +
	"\vCancelOrder\x12\x1c.e_product_v1.CancelOrderReq\x1a\x1c.e_product_v1.CancelOrderRep\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/key/provider/cancel\x12c\n" +
	"\aCatalog\x12\x1b.e_product_v1.GetCatalogReq\x1a\x1b.e_product_v1.GetCatalogRep\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/catalog/{provider_id}B\x0fZ\r/e_product_v1b\x06proto3"

var (
	file_e_product_e_product_v1_proto_rawDescOnce sync.Once
	file_e_product_e_product_v1_proto_rawDescData []byte
)

func file_e_product_e_product_v1_proto_rawDescGZIP() []byte {
	file_e_product_e_product_v1_proto_rawDescOnce.Do(func() {
		file_e_product_e_product_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_e_product_e_product_v1_proto_rawDesc), len(file_e_product_e_product_v1_proto_rawDesc)))
	})
	return file_e_product_e_product_v1_proto_rawDescData
}

var file_e_product_e_product_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_e_product_e_product_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_e_product_e_product_v1_proto_goTypes = []any{
	(KeyStatus)(0),                  // 0: e_product_v1.KeyStatus
	(*KeyItem)(nil),                 // 1: e_product_v1.KeyItem
	(*LoadKeyReq)(nil),              // 2: e_product_v1.LoadKeyReq
	(*KeyResponseItem)(nil),         // 3: e_product_v1.KeyResponseItem
	(*LoadKeyRep)(nil),              // 4: e_product_v1.LoadKeyRep
	(*KeyListReq)(nil),              // 5: e_product_v1.KeyListReq
	(*KeyListRep)(nil),              // 6: e_product_v1.KeyListRep
	(*KeyGetReq)(nil),               // 7: e_product_v1.KeyGetReq
	(*KeyGetRep)(nil),               // 8: e_product_v1.KeyGetRep
	(*KeyActivateReq)(nil),          // 9: e_product_v1.KeyActivateReq
	(*KeyActivateRep)(nil),          // 10: e_product_v1.KeyActivateRep
	(*GetByProductIDReq)(nil),       // 11: e_product_v1.GetByProductIDReq
	(*GetByProductIDRep)(nil),       // 12: e_product_v1.GetByProductIDRep
	(*GetCatalogReq)(nil),           // 13: e_product_v1.GetCatalogReq
	(*GetCatalogRep)(nil),           // 14: e_product_v1.GetCatalogRep
	(*CatalogItem)(nil),             // 15: e_product_v1.CatalogItem
	(*CreateOrderReq)(nil),          // 16: e_product_v1.CreateOrderReq
	(*CreateOrderRep)(nil),          // 17: e_product_v1.CreateOrderRep
	(*CancelOrderReq)(nil),          // 18: e_product_v1.CancelOrderReq
	(*CancelOrderRep)(nil),          // 19: e_product_v1.CancelOrderRep
	(*timestamppb.Timestamp)(nil),   // 20: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 21: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 22: common.PaginationInfoSt
}
var file_e_product_e_product_v1_proto_depIdxs = []int32{
	1,  // 0: e_product_v1.LoadKeyReq.keys:type_name -> e_product_v1.KeyItem
	20, // 1: e_product_v1.KeyResponseItem.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: e_product_v1.KeyResponseItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: e_product_v1.KeyResponseItem.status:type_name -> e_product_v1.KeyStatus
	3,  // 4: e_product_v1.LoadKeyRep.keys:type_name -> e_product_v1.KeyResponseItem
	0,  // 5: e_product_v1.KeyListReq.status:type_name -> e_product_v1.KeyStatus
	21, // 6: e_product_v1.KeyListReq.list_params:type_name -> common.ListParamsSt
	3,  // 7: e_product_v1.KeyListRep.keys:type_name -> e_product_v1.KeyResponseItem
	22, // 8: e_product_v1.KeyListRep.pagination_info:type_name -> common.PaginationInfoSt
	3,  // 9: e_product_v1.KeyGetRep.key:type_name -> e_product_v1.KeyResponseItem
	15, // 10: e_product_v1.GetCatalogRep.items:type_name -> e_product_v1.CatalogItem
	0,  // 11: e_product_v1.CreateOrderRep.status:type_name -> e_product_v1.KeyStatus
	2,  // 12: e_product_v1.Key.Load:input_type -> e_product_v1.LoadKeyReq
	5,  // 13: e_product_v1.Key.List:input_type -> e_product_v1.KeyListReq
	7,  // 14: e_product_v1.Key.Get:input_type -> e_product_v1.KeyGetReq
	9,  // 15: e_product_v1.Key.Activate:input_type -> e_product_v1.KeyActivateReq
	11, // 16: e_product_v1.Key.GetByProductID:input_type -> e_product_v1.GetByProductIDReq
	16, // 17: e_product_v1.Key.CreateOrder:input_type -> e_product_v1.CreateOrderReq
	18, // 18: e_product_v1.Key.CancelOrder:input_type -> e_product_v1.CancelOrderReq
	13, // 19: e_product_v1.Key.Catalog:input_type -> e_product_v1.GetCatalogReq
	4,  // 20: e_product_v1.Key.Load:output_type -> e_product_v1.LoadKeyRep
	6,  // 21: e_product_v1.Key.List:output_type -> e_product_v1.KeyListRep
	8,  // 22: e_product_v1.Key.Get:output_type -> e_product_v1.KeyGetRep
	10, // 23: e_product_v1.Key.Activate:output_type -> e_product_v1.KeyActivateRep
	12, // 24: e_product_v1.Key.GetByProductID:output_type -> e_product_v1.GetByProductIDRep
	17, // 25: e_product_v1.Key.CreateOrder:output_type -> e_product_v1.CreateOrderRep
	19, // 26: e_product_v1.Key.CancelOrder:output_type -> e_product_v1.CancelOrderRep
	14, // 27: e_product_v1.Key.Catalog:output_type -> e_product_v1.GetCatalogRep
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_e_product_e_product_v1_proto_init() }
func file_e_product_e_product_v1_proto_init() {
	if File_e_product_e_product_v1_proto != nil {
		return
	}
	file_e_product_e_product_v1_proto_msgTypes[4].OneofWrappers = []any{}
	file_e_product_e_product_v1_proto_msgTypes[7].OneofWrappers = []any{}
	file_e_product_e_product_v1_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e_product_e_product_v1_proto_rawDesc), len(file_e_product_e_product_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_e_product_e_product_v1_proto_goTypes,
		DependencyIndexes: file_e_product_e_product_v1_proto_depIdxs,
		EnumInfos:         file_e_product_e_product_v1_proto_enumTypes,
		MessageInfos:      file_e_product_e_product_v1_proto_msgTypes,
	}.Build()
	File_e_product_e_product_v1_proto = out.File
	file_e_product_e_product_v1_proto_goTypes = nil
	file_e_product_e_product_v1_proto_depIdxs = nil
}
