// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: e_product/e_product_v1.proto

package e_product_v1

import (
	common "github.com/mechta-market/e-product/pkg/proto/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyStatus int32

const (
	KeyStatus_new       KeyStatus = 0
	KeyStatus_activated KeyStatus = 1
	KeyStatus_cancelled KeyStatus = 2
)

// Enum value maps for KeyStatus.
var (
	KeyStatus_name = map[int32]string{
		0: "new",
		1: "activated",
		2: "cancelled",
	}
	KeyStatus_value = map[string]int32{
		"new":       0,
		"activated": 1,
		"cancelled": 2,
	}
)

func (x KeyStatus) Enum() *KeyStatus {
	p := new(KeyStatus)
	*p = x
	return p
}

func (x KeyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_e_product_e_product_v1_proto_enumTypes[0].Descriptor()
}

func (KeyStatus) Type() protoreflect.EnumType {
	return &file_e_product_e_product_v1_proto_enumTypes[0]
}

func (x KeyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyStatus.Descriptor instead.
func (KeyStatus) EnumDescriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{0}
}

// Load
type KeyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyItem) Reset() {
	*x = KeyItem{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyItem) ProtoMessage() {}

func (x *KeyItem) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyItem.ProtoReflect.Descriptor instead.
func (*KeyItem) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{0}
}

func (x *KeyItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LoadKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KeyItem             `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadKeyReq) Reset() {
	*x = LoadKeyReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadKeyReq) ProtoMessage() {}

func (x *LoadKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadKeyReq.ProtoReflect.Descriptor instead.
func (*LoadKeyReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{1}
}

func (x *LoadKeyReq) GetKeys() []*KeyItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyResponseItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderId        string                 `protobuf:"bytes,2,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProductId         string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CustomerPhone     string                 `protobuf:"bytes,6,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	Status            KeyStatus              `protobuf:"varint,7,opt,name=status,proto3,enum=e_product_v1.KeyStatus" json:"status,omitempty"`
	OrderId           string                 `protobuf:"bytes,8,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProviderProductId string                 `protobuf:"bytes,9,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	ProviderOrderId   string                 `protobuf:"bytes,10,opt,name=provider_order_id,json=providerOrderId,proto3" json:"provider_order_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *KeyResponseItem) Reset() {
	*x = KeyResponseItem{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponseItem) ProtoMessage() {}

func (x *KeyResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponseItem.ProtoReflect.Descriptor instead.
func (*KeyResponseItem) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{2}
}

func (x *KeyResponseItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyResponseItem) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *KeyResponseItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyResponseItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KeyResponseItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KeyResponseItem) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *KeyResponseItem) GetStatus() KeyStatus {
	if x != nil {
		return x.Status
	}
	return KeyStatus_new
}

func (x *KeyResponseItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *KeyResponseItem) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

func (x *KeyResponseItem) GetProviderOrderId() string {
	if x != nil {
		return x.ProviderOrderId
	}
	return ""
}

// List
type KeyListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    *string                `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3,oneof" json:"provider_id,omitempty"`
	Status        *KeyStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=e_product_v1.KeyStatus,oneof" json:"status,omitempty"`
	OrderId       *string                `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3,oneof" json:"order_id,omitempty"`
	ProductId     *string                `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,5,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyListReq) Reset() {
	*x = KeyListReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListReq) ProtoMessage() {}

func (x *KeyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListReq.ProtoReflect.Descriptor instead.
func (*KeyListReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{3}
}

func (x *KeyListReq) GetProviderId() string {
	if x != nil && x.ProviderId != nil {
		return *x.ProviderId
	}
	return ""
}

func (x *KeyListReq) GetStatus() KeyStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return KeyStatus_new
}

func (x *KeyListReq) GetOrderId() string {
	if x != nil && x.OrderId != nil {
		return *x.OrderId
	}
	return ""
}

func (x *KeyListReq) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

func (x *KeyListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

type KeyListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Keys           []*KeyResponseItem       `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,2,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyListRep) Reset() {
	*x = KeyListRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListRep) ProtoMessage() {}

func (x *KeyListRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListRep.ProtoReflect.Descriptor instead.
func (*KeyListRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{4}
}

func (x *KeyListRep) GetKeys() []*KeyResponseItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeyListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

// Get
type KeyGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGetReq) Reset() {
	*x = KeyGetReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGetReq) ProtoMessage() {}

func (x *KeyGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGetReq.ProtoReflect.Descriptor instead.
func (*KeyGetReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{5}
}

func (x *KeyGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KeyActivateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CustomerPhone string                 `protobuf:"bytes,2,opt,name=customer_phone,json=customerPhone,proto3" json:"customer_phone,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyActivateReq) Reset() {
	*x = KeyActivateReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyActivateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyActivateReq) ProtoMessage() {}

func (x *KeyActivateReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyActivateReq.ProtoReflect.Descriptor instead.
func (*KeyActivateReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{6}
}

func (x *KeyActivateReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *KeyActivateReq) GetCustomerPhone() string {
	if x != nil {
		return x.CustomerPhone
	}
	return ""
}

func (x *KeyActivateReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type KeyActivateRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyActivateRep) Reset() {
	*x = KeyActivateRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyActivateRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyActivateRep) ProtoMessage() {}

func (x *KeyActivateRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyActivateRep.ProtoReflect.Descriptor instead.
func (*KeyActivateRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{7}
}

func (x *KeyActivateRep) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KeyCancelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyCancelReq) Reset() {
	*x = KeyCancelReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCancelReq) ProtoMessage() {}

func (x *KeyCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCancelReq.ProtoReflect.Descriptor instead.
func (*KeyCancelReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{8}
}

func (x *KeyCancelReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type KeyCancelRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyCancelRep) Reset() {
	*x = KeyCancelRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyCancelRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyCancelRep) ProtoMessage() {}

func (x *KeyCancelRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyCancelRep.ProtoReflect.Descriptor instead.
func (*KeyCancelRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{9}
}

func (x *KeyCancelRep) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCatalogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogReq) Reset() {
	*x = GetCatalogReq{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogReq) ProtoMessage() {}

func (x *GetCatalogReq) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogReq.ProtoReflect.Descriptor instead.
func (*GetCatalogReq) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{10}
}

func (x *GetCatalogReq) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type GetCatalogRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRep) Reset() {
	*x = GetCatalogRep{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRep) ProtoMessage() {}

func (x *GetCatalogRep) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRep.ProtoReflect.Descriptor instead.
func (*GetCatalogRep) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{11}
}

func (x *GetCatalogRep) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CatalogItem struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ProviderProductId         string                 `protobuf:"bytes,1,opt,name=provider_product_id,json=providerProductId,proto3" json:"provider_product_id,omitempty"`
	ProviderExternalProductId string                 `protobuf:"bytes,2,opt,name=provider_external_product_id,json=providerExternalProductId,proto3" json:"provider_external_product_id,omitempty"`
	Name                      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Desc                      string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CatalogItem) Reset() {
	*x = CatalogItem{}
	mi := &file_e_product_e_product_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogItem) ProtoMessage() {}

func (x *CatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_e_product_e_product_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogItem.ProtoReflect.Descriptor instead.
func (*CatalogItem) Descriptor() ([]byte, []int) {
	return file_e_product_e_product_v1_proto_rawDescGZIP(), []int{12}
}

func (x *CatalogItem) GetProviderProductId() string {
	if x != nil {
		return x.ProviderProductId
	}
	return ""
}

func (x *CatalogItem) GetProviderExternalProductId() string {
	if x != nil {
		return x.ProviderExternalProductId
	}
	return ""
}

func (x *CatalogItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CatalogItem) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_e_product_e_product_v1_proto protoreflect.FileDescriptor

const file_e_product_e_product_v1_proto_rawDesc = "" +
	"\n" +
	"\x1ce_product/e_product_v1.proto\x12\fe_product_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x13common/common.proto\">\n" +
	"\aKeyItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"7\n" +
	"\n" +
	"LoadKeyReq\x12)\n" +
	"\x04keys\x18\x01 \x03(\v2\x15.e_product_v1.KeyItemR\x04keys\"\xa6\x03\n" +
	"\x0fKeyResponseItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vprovider_id\x18\x02 \x01(\tR\n" +
	"providerId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0ecustomer_phone\x18\x06 \x01(\tR\rcustomerPhone\x12/\n" +
	"\x06status\x18\a \x01(\x0e2\x17.e_product_v1.KeyStatusR\x06status\x12\x19\n" +
	"\border_id\x18\b \x01(\tR\aorderId\x12.\n" +
	"\x13provider_product_id\x18\t \x01(\tR\x11providerProductId\x12*\n" +
	"\x11provider_order_id\x18\n" +
	" \x01(\tR\x0fproviderOrderId\"\x9a\x02\n" +
	"\n" +
	"KeyListReq\x12$\n" +
	"\vprovider_id\x18\x01 \x01(\tH\x00R\n" +
	"providerId\x88\x01\x01\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.e_product_v1.KeyStatusH\x01R\x06status\x88\x01\x01\x12\x1e\n" +
	"\border_id\x18\x03 \x01(\tH\x02R\aorderId\x88\x01\x01\x12\"\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tH\x03R\tproductId\x88\x01\x01\x125\n" +
	"\vlist_params\x18\x05 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParamsB\x0e\n" +
	"\f_provider_idB\t\n" +
	"\a_statusB\v\n" +
	"\t_order_idB\r\n" +
	"\v_product_id\"\x82\x01\n" +
	"\n" +
	"KeyListRep\x121\n" +
	"\x04keys\x18\x01 \x03(\v2\x1d.e_product_v1.KeyResponseItemR\x04keys\x12A\n" +
	"\x0fpagination_info\x18\x02 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\"\x1b\n" +
	"\tKeyGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\x0eKeyActivateReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12%\n" +
	"\x0ecustomer_phone\x18\x02 \x01(\tR\rcustomerPhone\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"&\n" +
	"\x0eKeyActivateRep\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\")\n" +
	"\fKeyCancelReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x1e\n" +
	"\fKeyCancelRep\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\rGetCatalogReq\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"@\n" +
	"\rGetCatalogRep\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.e_product_v1.CatalogItemR\x05items\"\xa6\x01\n" +
	"\vCatalogItem\x12.\n" +
	"\x13provider_product_id\x18\x01 \x01(\tR\x11providerProductId\x12?\n" +
	"\x1cprovider_external_product_id\x18\x02 \x01(\tR\x19providerExternalProductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc*2\n" +
	"\tKeyStatus\x12\a\n" +
	"\x03new\x10\x00\x12\r\n" +
	"\tactivated\x10\x01\x12\r\n" +
	"\tcancelled\x10\x022\x8d\x04\n" +
	"\x03Key\x12I\n" +
	"\x04Load\x12\x18.e_product_v1.LoadKeyReq\x1a\x16.google.protobuf.Empty\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/key\x12H\n" +
	"\x04List\x12\x18.e_product_v1.KeyListReq\x1a\x18.e_product_v1.KeyListRep\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/key\x12P\n" +
	"\x03Get\x12\x17.e_product_v1.KeyGetReq\x1a\x1d.e_product_v1.KeyResponseItem\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/key/{id}\x12`\n" +
	"\bActivate\x12\x1c.e_product_v1.KeyActivateReq\x1a\x1c.e_product_v1.KeyActivateRep\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/key/activate\x12X\n" +
	"\x06Cancel\x12\x1a.e_product_v1.KeyCancelReq\x1a\x1a.e_product_v1.KeyCancelRep\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/key/cancel\x12c\n" +
	"\aCatalog\x12\x1b.e_product_v1.GetCatalogReq\x1a\x1b.e_product_v1.GetCatalogRep\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/catalog/{provider_id}B\x0fZ\r/e_product_v1b\x06proto3"

var (
	file_e_product_e_product_v1_proto_rawDescOnce sync.Once
	file_e_product_e_product_v1_proto_rawDescData []byte
)

func file_e_product_e_product_v1_proto_rawDescGZIP() []byte {
	file_e_product_e_product_v1_proto_rawDescOnce.Do(func() {
		file_e_product_e_product_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_e_product_e_product_v1_proto_rawDesc), len(file_e_product_e_product_v1_proto_rawDesc)))
	})
	return file_e_product_e_product_v1_proto_rawDescData
}

var file_e_product_e_product_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_e_product_e_product_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_e_product_e_product_v1_proto_goTypes = []any{
	(KeyStatus)(0),                  // 0: e_product_v1.KeyStatus
	(*KeyItem)(nil),                 // 1: e_product_v1.KeyItem
	(*LoadKeyReq)(nil),              // 2: e_product_v1.LoadKeyReq
	(*KeyResponseItem)(nil),         // 3: e_product_v1.KeyResponseItem
	(*KeyListReq)(nil),              // 4: e_product_v1.KeyListReq
	(*KeyListRep)(nil),              // 5: e_product_v1.KeyListRep
	(*KeyGetReq)(nil),               // 6: e_product_v1.KeyGetReq
	(*KeyActivateReq)(nil),          // 7: e_product_v1.KeyActivateReq
	(*KeyActivateRep)(nil),          // 8: e_product_v1.KeyActivateRep
	(*KeyCancelReq)(nil),            // 9: e_product_v1.KeyCancelReq
	(*KeyCancelRep)(nil),            // 10: e_product_v1.KeyCancelRep
	(*GetCatalogReq)(nil),           // 11: e_product_v1.GetCatalogReq
	(*GetCatalogRep)(nil),           // 12: e_product_v1.GetCatalogRep
	(*CatalogItem)(nil),             // 13: e_product_v1.CatalogItem
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 15: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 16: common.PaginationInfoSt
	(*emptypb.Empty)(nil),           // 17: google.protobuf.Empty
}
var file_e_product_e_product_v1_proto_depIdxs = []int32{
	1,  // 0: e_product_v1.LoadKeyReq.keys:type_name -> e_product_v1.KeyItem
	14, // 1: e_product_v1.KeyResponseItem.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: e_product_v1.KeyResponseItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: e_product_v1.KeyResponseItem.status:type_name -> e_product_v1.KeyStatus
	0,  // 4: e_product_v1.KeyListReq.status:type_name -> e_product_v1.KeyStatus
	15, // 5: e_product_v1.KeyListReq.list_params:type_name -> common.ListParamsSt
	3,  // 6: e_product_v1.KeyListRep.keys:type_name -> e_product_v1.KeyResponseItem
	16, // 7: e_product_v1.KeyListRep.pagination_info:type_name -> common.PaginationInfoSt
	13, // 8: e_product_v1.GetCatalogRep.items:type_name -> e_product_v1.CatalogItem
	2,  // 9: e_product_v1.Key.Load:input_type -> e_product_v1.LoadKeyReq
	4,  // 10: e_product_v1.Key.List:input_type -> e_product_v1.KeyListReq
	6,  // 11: e_product_v1.Key.Get:input_type -> e_product_v1.KeyGetReq
	7,  // 12: e_product_v1.Key.Activate:input_type -> e_product_v1.KeyActivateReq
	9,  // 13: e_product_v1.Key.Cancel:input_type -> e_product_v1.KeyCancelReq
	11, // 14: e_product_v1.Key.Catalog:input_type -> e_product_v1.GetCatalogReq
	17, // 15: e_product_v1.Key.Load:output_type -> google.protobuf.Empty
	5,  // 16: e_product_v1.Key.List:output_type -> e_product_v1.KeyListRep
	3,  // 17: e_product_v1.Key.Get:output_type -> e_product_v1.KeyResponseItem
	8,  // 18: e_product_v1.Key.Activate:output_type -> e_product_v1.KeyActivateRep
	10, // 19: e_product_v1.Key.Cancel:output_type -> e_product_v1.KeyCancelRep
	12, // 20: e_product_v1.Key.Catalog:output_type -> e_product_v1.GetCatalogRep
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_e_product_e_product_v1_proto_init() }
func file_e_product_e_product_v1_proto_init() {
	if File_e_product_e_product_v1_proto != nil {
		return
	}
	file_e_product_e_product_v1_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_e_product_e_product_v1_proto_rawDesc), len(file_e_product_e_product_v1_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_e_product_e_product_v1_proto_goTypes,
		DependencyIndexes: file_e_product_e_product_v1_proto_depIdxs,
		EnumInfos:         file_e_product_e_product_v1_proto_enumTypes,
		MessageInfos:      file_e_product_e_product_v1_proto_msgTypes,
	}.Build()
	File_e_product_e_product_v1_proto = out.File
	file_e_product_e_product_v1_proto_goTypes = nil
	file_e_product_e_product_v1_proto_depIdxs = nil
}
